#' @title
#' First Order Dominance Analysis on Partially Ordered Sets
#'
#' @description
#' Performs First Order Dominance (FOD) analysis to evaluate structural
#' relationships and distributions over one or multiple Partially Ordered Sets (POSets).
#' The function dispatches the computation to a high-performance C++ backend.
#'
#' @details
#' The analysis can compute up to four different metrics concurrently:
#' \itemize{
#'   \item \code{"Dominance"}: Computes the basic First Order Dominance.
#'   \item \code{"MannWhitneyDominance"}: Computes dominance over distributions using Mann-Whitney.
#'   \item \code{"MannWhitneyInferentialDominance"}: Computes inferential dominance requiring subpopulation counts.
#'   \item \code{"MRP"}: Estimates the Mutual Ranking Probability matrix of the
#'   poset (element by element, over the same sample of linear extensions).
#'   Requires a single POSet; its result is the raw matrix, without the FOD
#'   post-processing applied to the other metrics.
#' }
#'
#' If multiple POSets are provided (as a list), a separator \code{sep} must be specified
#' to correctly parse the labels of the observation values.
#'
#' @param posets An object of S4 class `POSet`, or a list of `LinearPOSet` objects.
#' @param freq_matrix A numeric matrix (double or integer) representing adjacency
#' frequencies. Must have unique, non-empty row names (observation values) and
#' column names (groups); NA and negative values are not allowed.
#' @param metrics A character vector specifying the metrics to compute.
#' Allowed values are \code{"Dominance"}, \code{"MannWhitneyDominance"},
#' \code{"MannWhitneyInferentialDominance"} and \code{"MRP"}.
#' Default is \code{"Dominance"}.
#' @param subpopulation_count A numeric vector containing the subpopulation sizes
#' (one per column of \code{freq_matrix}). Mandatory if
#' \code{"MannWhitneyInferentialDominance"} is selected; otherwise ignored.
#' @param total_bins Integer defining the number of bins for distribution analysis.
#' Mandatory (> 0) when a Mann-Whitney metric is selected; default is \code{0L}.
#' @param count Optional positive integer. An upper limit for the number of linear
#' extensions to generate (triggers MCMC sampling). When \code{linear_extensions}
#' is provided it is mandatory and indicates the number of linear extensions
#' generated by EACH chain (total = count * number of chains).
#' @param seed Optional integer. A seed for the random number generator; can only
#' be provided together with \code{count}. When \code{linear_extensions} is
#' provided it may also be an integer vector with exactly one seed per chain
#' (i.e. one per column of \code{linear_extensions}).
#' The generator seeds are 64-bit: to use a value above 2^53 (which R cannot
#' represent exactly) pass it as a string of decimal digits, e.g. `"12345678901234567890"`.
#' @param output_interval_in_sec Optional non-negative integer. Refresh rate
#' (in seconds) for logging to the R console.
#' @param sep Non-empty character string used as a separator when evaluating
#' multiple POSets. Default is \code{"_"}.
#' @param tolerance Positive numeric value specifying the double precision
#' tolerance. Default is \code{1e-9}.
#' @param alpha Optional numeric vector of cut thresholds. If \code{NULL} (default),
#' all the natural cut levels emerging from the data are used.
#' @param linear_extensions Optional character matrix enabling the PARALLEL
#' multi-chain Bubley-Dyer evaluation. Each COLUMN is a valid linear extension
#' of the poset, expressed as element names (one row per poset element), and
#' becomes the starting point of an independent MCMC chain (\code{count}
#' linear extensions per chain). Requires a single POSet and \code{count}.
#' If \code{NULL} (default) the classic single-generator behaviour is used.
#' @param n_threads Optional positive integer: number of worker threads used to
#' run the chains of the multi-chain evaluation. \code{NULL} (default) means
#' automatic (all available hardware threads); the value is capped at the
#' number of chains. It does NOT affect the numerical results (which depend
#' only on the chains and their seeds), only the execution time. Ignored,
#' with a warning, when \code{linear_extensions} is \code{NULL}.
#'
#' @return
#' A named list with one entry per evaluated metric (each containing
#' \code{delta}, \code{bin}, \code{mintr.delta}, \code{global.approx},
#' \code{global.approx.corr}, \code{cell.approx}, \code{posets.ind},
#' \code{eqv.classes}, \code{quasi.orders}, \code{Zs}, \code{posets}),
#' plus the entry \code{LEType} (linear extension generator used) and the
#' attribute \code{le_count} (number of linear extensions processed).
#' When MCMC sampling is used the result also carries the attribute
#' \code{seed}: the 64-bit seed (or one per chain) actually used, as a string
#' of decimal digits. Passing it back to \code{seed} reproduces the result.
#' The \code{"MRP"} entry is different: it is the estimated Mutual Ranking
#' Probability matrix itself (poset elements on rows and columns), with no
#' FOD post-processing.
#'
#' @export
FirstOrderDominanceAnalysis <- function(posets,
                                        freq_matrix,
                                        metrics = c("Dominance"),
                                        subpopulation_count = NULL,
                                        total_bins = 0L,
                                        count = NULL,
                                        seed = NULL,
                                        output_interval_in_sec = NULL,
                                        sep = "_",
                                        tolerance = 1e-9,
                                        alpha = NULL,
                                        linear_extensions = NULL,
                                        n_threads = NULL) {

  # --------------------------------------------------------------------------
  # 0. Helper di validazione per gli interi scalari opzionali
  # --------------------------------------------------------------------------
  .check_opt_int <- function(x, name, min_value = 0) {
    if (is.null(x)) return(NULL)
    if (!is.numeric(x) || length(x) != 1L || is.na(x) || x != trunc(x)) {
      stop(sprintf("'%s' must be a single integer value (or NULL).", name), call. = FALSE)
    }
    if (x < min_value) {
      stop(sprintf("'%s' must be >= %d.", name, min_value), call. = FALSE)
    }
    if (x > .Machine$integer.max) {
      stop(sprintf("'%s' is too large (max %d).", name, .Machine$integer.max), call. = FALSE)
    }
    as.integer(x)
  }

  # --------------------------------------------------------------------------
  # 1. Validazione di POSet(s) ed estrazione dei puntatori
  # --------------------------------------------------------------------------
  if (is.list(posets)) {
    if (length(posets) == 0L) {
      stop("'posets' cannot be an empty list.")
    }
    poset_ptr <- lapply(posets, function(p) {
      if (!methods::is(p, "LinearPOSet")) {
        stop("All elements in the 'posets' list must be of S4 class 'LinearPOSet'")
      }
      if (typeof(p@ptr) != "externalptr") {
        stop("Invalid 'LinearPOSet' pointer (was the object serialized and reloaded?).")
      }
      return(p@ptr)
    })
  } else {
    if (!methods::is(posets, "POSet")) {
      stop("'posets' must be an object of S4 class 'POSet' or a list of 'LinearPOSet' objects")
    }
    if (typeof(posets@ptr) != "externalptr") {
      stop("Invalid 'POSet' pointer (was the object serialized and reloaded?).")
    }
    poset_ptr <- posets@ptr
  }

  # --------------------------------------------------------------------------
  # 2. Validazione della matrice delle frequenze
  # --------------------------------------------------------------------------
  if (!is.matrix(freq_matrix) || !is.numeric(freq_matrix)) {
    stop("'freq_matrix' must be a numeric matrix.")
  }
  if (nrow(freq_matrix) == 0L || ncol(freq_matrix) == 0L) {
    stop("'freq_matrix' cannot have zero rows or columns.")
  }
  if (anyNA(freq_matrix)) {
    stop("'freq_matrix' cannot contain NA/NaN values.")
  }
  if (any(freq_matrix < 0)) {
    stop("'freq_matrix' cannot contain negative values.")
  }
  rn <- rownames(freq_matrix)
  cn <- colnames(freq_matrix)
  if (is.null(rn) || is.null(cn)) {
    stop("'freq_matrix' must have both row names and column names.")
  }
  if (anyNA(rn) || any(!nzchar(rn))) {
    stop("Row names of 'freq_matrix' must be non-empty and not NA.")
  }
  if (anyNA(cn) || any(!nzchar(cn))) {
    stop("Column names of 'freq_matrix' must be non-empty and not NA.")
  }
  if (anyDuplicated(rn) > 0L) {
    stop("Row names of 'freq_matrix' (observation values) must be unique.")
  }
  if (anyDuplicated(cn) > 0L) {
    stop("Column names of 'freq_matrix' (groups) must be unique.")
  }

  # --------------------------------------------------------------------------
  # 3. Preparazione delle metriche (maschera booleana di lunghezza 3)
  # --------------------------------------------------------------------------
  if (!is.character(metrics) || length(metrics) == 0L || anyNA(metrics)) {
    stop("'metrics' must be a non-empty character vector without NA.")
  }
  allowed_metrics <- c("Dominance", "MannWhitneyDominance", "MannWhitneyInferentialDominance", "MRP")
  metrics <- match.arg(metrics, allowed_metrics, several.ok = TRUE)

  # Traduzione nel vettore logico di lunghezza 4 atteso dalla struct C++
  metrics_logical <- c(
    "Dominance" %in% metrics,
    "MannWhitneyDominance" %in% metrics,
    "MannWhitneyInferentialDominance" %in% metrics,
    "MRP" %in% metrics
  )

  # --------------------------------------------------------------------------
  # 4. Validazione di subpopulation_count (metrica inferenziale)
  # --------------------------------------------------------------------------
  if (metrics_logical[3]) {
    if (is.null(subpopulation_count)) {
      stop("'subpopulation_count' is mandatory when 'MannWhitneyInferentialDominance' is requested.")
    }
    if (!is.numeric(subpopulation_count) || anyNA(subpopulation_count)) {
      stop("'subpopulation_count' must be a numeric vector without NA.")
    }
    if (length(subpopulation_count) != ncol(freq_matrix)) {
      stop(sprintf("'subpopulation_count' must have one value per column of 'freq_matrix' (expected %d, got %d).",
                   ncol(freq_matrix), length(subpopulation_count)))
    }
    if (any(subpopulation_count <= 0)) {
      stop("'subpopulation_count' values must be strictly positive.")
    }
    subpopulation_count <- as.numeric(subpopulation_count)
  } else if (!is.null(subpopulation_count)) {
    warning("'subpopulation_count' is ignored unless 'MannWhitneyInferentialDominance' is requested.")
    subpopulation_count <- NULL
  }

  # --------------------------------------------------------------------------
  # 5. Validazione dei parametri scalari
  # --------------------------------------------------------------------------
  # total_bins: obbligatorio (> 0) solo per le metriche Mann-Whitney
  if (is.null(total_bins)) total_bins <- 0L
  if (!is.numeric(total_bins) || length(total_bins) != 1L || is.na(total_bins) ||
      total_bins != trunc(total_bins) || total_bins < 0 ||
      total_bins > .Machine$integer.max) {
    stop("'total_bins' must be a single non-negative integer.")
  }
  total_bins <- as.integer(total_bins)
  if ((metrics_logical[2] || metrics_logical[3]) && total_bins == 0L) {
    stop("'total_bins' must be > 0 when a Mann-Whitney metric is selected.")
  }

  # count, output_interval_in_sec: interi scalari opzionali
  count <- .check_opt_int(count, "count", min_value = 1)
  output_interval_in_sec <- .check_opt_int(output_interval_in_sec, "output_interval_in_sec", min_value = 0)

  # linear_extensions: matrice character opzionale che attiva la valutazione
  # multi-catena parallela (una colonna = una LE di partenza per catena).
  # La compatibilita' di ogni colonna con l'ordine parziale e' verificata dal
  # backend C++ (costruttore di LEGBubleyDyer).
  if (!is.null(linear_extensions)) {
    if (is.list(posets)) {
      stop("'linear_extensions' is not supported when multiple POSets are provided.")
    }
    if (!is.matrix(linear_extensions) || !is.character(linear_extensions)) {
      stop("'linear_extensions' must be a character matrix (each column is one linear extension).")
    }
    if (anyNA(linear_extensions) || any(!nzchar(linear_extensions))) {
      stop("'linear_extensions' cannot contain NA or empty strings.")
    }
    if (is.null(count)) {
      stop("'count' (number of linear extensions PER CHAIN) is mandatory when 'linear_extensions' is provided.")
    }
  }

  # n_threads: numero di worker per il ramo multi-catena (NULL = automatico).
  # Non influenza i risultati numerici, solo il tempo di esecuzione.
  if (!is.null(n_threads) && is.null(linear_extensions)) {
    warning("'n_threads' is ignored unless 'linear_extensions' is provided.")
    n_threads <- NULL
  }
  n_threads <- .check_opt_int(n_threads, "n_threads", min_value = 1)

  # seed: scalare, oppure (solo con 'linear_extensions') un vettore con
  # esattamente un seed per catena. I valori vengono convertiti in stringhe di
  # cifre decimali, l'unico formato che preserva i semi a 64 bit del backend.
  if (!is.null(seed) && !is.null(linear_extensions) && length(seed) > 1L) {
    if (length(seed) != ncol(linear_extensions)) {
      stop(sprintf("When 'seed' is a vector it must contain one seed per chain (expected %d, got %d).",
                   ncol(linear_extensions), length(seed)))
    }
  } else if (!is.null(seed) && length(seed) != 1L) {
    stop("'seed' must be a single value, or one value per chain when 'linear_extensions' is provided.")
  }
  seed <- .seed_to_character(seed)

  if (!is.null(seed) && is.null(count)) {
    stop("'seed' can only be provided when 'count' is specified.")
  }

  # sep: stringa singola non vuota (necessaria per lo split delle etichette
  # quando vengono passati piu' POSet)
  if (!is.character(sep) || length(sep) != 1L || is.na(sep) || !nzchar(sep)) {
    stop("'sep' must be a single non-empty character string.")
  }

  # tolerance: numerico scalare positivo e finito
  if (!is.numeric(tolerance) || length(tolerance) != 1L || is.na(tolerance) ||
      !is.finite(tolerance) || tolerance <= 0) {
    stop("'tolerance' must be a single positive finite number.")
  }

  # alpha: opzionale, vettore numerico senza NA
  if (!is.null(alpha)) {
    if (!is.numeric(alpha) || length(alpha) == 0L || anyNA(alpha)) {
      stop("'alpha' must be a non-empty numeric vector without NA (or NULL).")
    }
  }

  # --------------------------------------------------------------------------
  # 6. Esecuzione della .Call (solo la chiamata C++ e' dentro il tryCatch,
  #    cosi' gli errori del post-processing R non vengono etichettati come C++)
  # --------------------------------------------------------------------------
  result_c <- tryCatch(
    .Call(C_FirstOrderDominanceAnalysis,
          poset_ptr,
          freq_matrix,
          subpopulation_count,
          as.logical(metrics_logical), # Logical SEXP (TRUE/FALSE vector of length 4)
          total_bins,
          count,
          seed,
          output_interval_in_sec,
          sep,
          linear_extensions,
          n_threads),
    error = function(e) {
      stop(paste("Error during First Order Dominance Analysis in C++:", conditionMessage(e)),
           call. = FALSE)
    }
  )

  # --------------------------------------------------------------------------
  # 7. Post-processing dei risultati
  # --------------------------------------------------------------------------
  result <- list()
  # Calcolo del numero di decimali per l'arrotondamento basato sulla tolleranza (es. 1e-9 -> 9 cifre).
  # round() serve a neutralizzare l'errore floating-point di log10 (es. 8.999999 -> 9);
  # senza, il troncamento a intero produrrebbe una cifra in meno.
  digits_to_round <- max(0L, as.integer(round(-log10(tolerance))))

  for (k in metrics) {

    # Controllo di sicurezza: verifica che il codice C++ abbia restituito i dati per la metrica corrente
    if (is.null(result_c[[k]])) {
      stop(sprintf("The C++ result for metric '%s' is missing or NULL.", k))
    }

    # MRP: matrice elemento x elemento del poset (stima della Mutual Ranking
    # Probability), senza analisi FOD gruppo x gruppo: viene restituita cosi' com'e'.
    if (k == "MRP") {
      MRP.MATRIX <- result_c[[k]][["binMatrix"]]
      if (is.null(MRP.MATRIX)) {
        stop("The C++ result for metric 'MRP' is incomplete (binMatrix missing).")
      }
      result[[k]] <- MRP.MATRIX
      next
    }

    # Estrazione delle matrici prodotte dall'algoritmo C++
    FOD.MATRIX <- result_c[[k]][["fodMatrix"]] # Matrice di dominanza empirica/frequenze
    FOD.CLOSED <- result_c[[k]][["fodClosed"]] # Chiusura transitiva (matrice dei valori di dominanza)
    FOD.BIN <- result_c[[k]][["binMatrix"]]    # Matrice di valutazione per bin

    if (is.null(FOD.MATRIX) || is.null(FOD.CLOSED) || is.null(FOD.BIN)) {
      stop(sprintf("The C++ result for metric '%s' is incomplete (fodMatrix/fodClosed/binMatrix missing).", k))
    }

    # --- 1. APPLICAZIONE DELLA TOLLERANZA SULL'ERRORE DI APPROSSIMAZIONE ---
    # Calcolo del residuo assoluto cella per cella tra la dominanza e la sua chiusura
    APPROX.CELLS <- abs(FOD.MATRIX - FOD.CLOSED)
    # Correzione numerica: azzera i residui microscopici generati dall'approssimazione macchina
    APPROX.CELLS[APPROX.CELLS < tolerance] <- 0

    # Calcolo dei denominatori globali e corretti (escludendo la diagonale principale)
    sum_fod <- sum(FOD.MATRIX)
    denom_corr <- sum_fod - nrow(FOD.MATRIX)

    # Calcolo degli indici globali di approssimazione con protezione da divisioni per zero
    APPROX.TOT <- if (sum_fod == 0) NA_real_ else sum(APPROX.CELLS) / sum_fod
    APPROX.TOT.CORR <- if (denom_corr == 0) NA_real_ else sum(APPROX.CELLS) / denom_corr

    # --- 2. GESTIONE E ARROTONDAMENTO DELLA SOGLIA ALPHA ---
    # Estrae i valori unici dalla chiusura transitiva e li arrotonda per evitare duplicati infinitesimi
    alpha_tmp <- sort(unique(round(c(FOD.CLOSED), digits_to_round)))

    if (is.null(alpha)) {
      # Se l'utente non ha specificato alpha, usiamo tutti i livelli di taglio naturali emersi dai dati
      alpha_loop <- alpha_tmp
    } else {
      # Se l'utente fornisce alpha esterni, cerchiamo per ognuno il valore più vicino nei dati,
      # applicando la tolleranza per gestire in sicurezza i minimi scostamenti negativi
      alpha_loop <- sapply(alpha, function(x) {
        res <- alpha_tmp - x
        res[res < -tolerance] <- Inf
        alpha_tmp[which.min(res)]
      })
    }
    rm(alpha_tmp)
    alpha_loop <- unique(alpha_loop) # Rimuove eventuali alpha sovrapposti dopo la mappatura

    # --- 3. COSTRUZIONE DEL QUASI-ORDINE (SOGLIA DELTA-ALPHA) ---
    # Filtra la matrice rispetto alla soglia alpha corrente. L'aggiunta di '+ tolerance'
    # garantisce la robustezza del confronto logico (>=) contro i falsi negativi floating-point.
    # NOTA MATEMATICA: L'output logico rappresenta un QUASI-ORDINE (riflessivo e transitivo, ma NON antisimmetrico)
    quasi.order <- lapply(alpha_loop, function(a) (FOD.CLOSED + tolerance) >= a)
    names(quasi.order) <- alpha_loop

    # --- 4. COLLASSO IN CLASSI DI EQUIVALENZA E GENERAZIONE DEI POSET QUOZIENTE ---
    # Questo blocco trasforma il quasi-ordine in un POSET vero e proprio eliminando
    # i cicli di dominanza reciproca (A <= B e B <= A) causati da profili equivalenti.
    orders <- lapply(quasi.order, function(m) {

      # FIX NUMERICO (Riflessività): Un quasi-ordine deve essere riflessivo per definizione (A <= A).
      # A causa di approssimazioni microscopiche floating-point nel backend C++ (es. valori 0.4999000
      # invece di 0.5), il confronto logico con la soglia alpha può far saltare la diagonale,
      # impostando erroneamente alcune celle a FALSE. Forziamo TRUE sulla diagonale principale
      # per sanare l'instabilità numerica ed evitare falsi negativi nel raggruppamento.
      diag(m) <- TRUE

      # SOLUZIONE ALGEBRICA (Dominanza Reciproca): Due elementi appartengono alla stessa classe
      # di equivalenza se e solo se si dominano a vicenda (A <= B E B <= A). Calcoliamo l'intersezione
      # logica tra la matrice m e la sua trasposta t(m) per mappare esattamente le simmetrie (i cicli).
      # Questo sostituisce il vecchio 'duplicated(m)', che falliva se la diagonale era corrotta.
      equiv_matrix <- m & t(m)

      # Identifichiamo le righe uniche della matrice di simmetria: ogni riga unica rappresenta
      # matematicamente una classe di equivalenza (un macro-nodo nel grafo quoziente).
      cases <- which(!duplicated(equiv_matrix))
      groups <- equiv_matrix[cases, , drop = FALSE]

      # --- GESTIONE DEI NOMI DEI MACRO-NODI ---
      n_groups <- nrow(groups)
      solo <- rowSums(groups) == 1 # TRUE se l'elemento è da solo nella sua classe
      rownames(groups) <- character(n_groups)

      # Se l'elemento è isolato, mantiene il suo nome originale del dataset
      if (any(solo)) {
        rownames(groups)[solo] <- colnames(m)[apply(groups[solo, , drop = FALSE], 1, which)]
      }
      # Se più elementi collassano insieme, prendono un nome collettivo sequenziale (G1, G2, ...)
      if (any(!solo)) {
        rownames(groups)[!solo] <- paste0("G", 1:sum(!solo))
      }
      colnames(groups) <- colnames(m)

      # --- COSTRUZIONE DELLA MATRICE Z QUOZIENTE ---
      # Estraiamo la sottomatrice quadrata ridotta prendendo un solo elemento rappresentativo (cases)
      # per ogni classe. Avendo rimosso tutte le dominanze reciproche tramite il collasso precedente,
      # questa matrice quoziente soddisfa rigorosamente la proprietà di ANTISIMMETRIA.
      res <- m[cases, cases, drop = FALSE]
      rownames(res) <- colnames(res) <- rownames(groups)
      class(res) <- "incidence" # Assegnazione della classe per l'algebra dei poset del pacchetto

      # Restituiamo sia la matrice di appartenenza alle classi che la matrice Z antisimmetrica
      return(list(equiv.classes = groups, incidence = res))
    })

    # --- 5. ESTRAZIONE STRUTTURATA DEI RISULTATI ---
    # Estrae in modo isolato e pulito le classi di equivalenza per ogni alpha
    equiv.classes <- lapply(orders, `[[`, "equiv.classes")

    # Estrae l'oggetto Z: ogni Z[[as.character(alpha)]] contiene la MATRICE DI INCIDENZA del POSET quoziente
    Z <- lapply(orders, `[[`, "incidence")
    names(equiv.classes) <- names(Z) <- alpha_loop

    # Generazione dell'oggetto G: converte ogni matrice di incidenza in un oggetto S4 "POSet"
    G <- lapply(Z, poseticDataAnalysis::POSetFromDominance)

    # --- 6. CALCOLO DEGLI INDICATORI COMBINATORI DEL POSET ---
    cardinalities <- sapply(Z, nrow)                             # Numero di macro-nodi nel poset (classi di equivalenza)
    comparabilities <- sapply(Z, function(z) sum(z) - nrow(z))   # Numero di coppie ordinate (escludendo la riflessività)
    # Calcolo delle coppie incomparabili (Combinatorio totale delle coppie possibili meno le comparabilità)
    incomparabilities <- cardinalities * (cardinalities - 1) / 2 - comparabilities

    # Calcolo del rapporto di comparabilità. Se le incomparabilità sono 0 (ordine totale), assegna NA
    # per evitare errori di divisione per zero (Inf o NaN)
    ci_ratio <- ifelse(incomparabilities == 0, NA_real_, comparabilities / incomparabilities)

    # Compilazione del data frame degli indicatori strutturali per il livello alpha corrente
    indicators <- data.frame(
      alpha             = alpha_loop,
      cardinality       = cardinalities,
      comparabilities   = comparabilities,
      incomparabilities = incomparabilities,
      ci.ratio          = ci_ratio
    )
    rownames(indicators) <- NULL

    # --- 7. STOCCAGGIO FINALE DELL'OUTPUT DELLA METRICA K ---
    r <- list(
      "delta"             = FOD.MATRIX,          # Matrice di dominanza iniziale
      "bin"               = FOD.BIN,
      "mintr.delta"       = FOD.CLOSED,          # Chiusura transitiva (matrice dei valori)
      "global.approx"     = APPROX.TOT,          # Indice di discrepanza globale
      "global.approx.corr"= APPROX.TOT.CORR,     # Indice di discrepanza corretto
      "cell.approx"       = APPROX.CELLS,        # Matrice delle discrepanze locali
      "posets.ind"        = indicators,          # Data frame degli indicatori strutturali combinatori
      "eqv.classes"       = equiv.classes,       # Mappatura dei nodi equivalenti (raggruppamenti)
      "quasi.orders"      = quasi.order,         # Restituisce i quasi-ordini booleani prima del collasso
      "Zs"                = Z,                   # Matrici di copertura (struttura grafica del poset)
      "posets"            = G                    # POSets
    )

    # Salva il blocco di analisi completo sotto la chiave della metrica corrente (k)
    result[[k]] <- r
  }

  # Metadati restituiti dal backend C++ (prima venivano scartati)
  result[["LEType"]] <- result_c[["LEType"]]
  attr(result, "le_count") <- attr(result_c, "le_count")
  # Seme (o semi, uno per catena) usato dal campionamento MCMC, come stringa:
  # ripassarlo a 'seed' riproduce esattamente questo risultato. Assente con
  # l'enumerazione esatta, che non usa numeri casuali.
  attr(result, "seed") <- attr(result_c, "seed")

  return(result)
}
